services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - 5678:5678
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=n8n.monphi.ch
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.monphi.ch/
      - GENERIC_TIMEZONE=Europe/Zurich
      - TZ=Europe/Zurich
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - containers
    restart: unless-stopped

volumes:
  n8n_data:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.86.10,nfsvers=3,nolock,hard,rw"
      device: ":/var/nfs/shared/Docker/n8n/data"

networks:
  containers:
    external: true
